pushd "%SRC_DIR%"\python

SET ARROW_HOME=%LIBRARY_PREFIX%
SET SETUPTOOLS_SCM_PRETEND_VERSION=%PKG_VERSION%
SET PYARROW_BUILD_TYPE=release
SET PYARROW_WITH_ACERO=1
SET PYARROW_WITH_S3=1
SET PYARROW_WITH_SUBSTRAIT=1
SET PYARROW_WITH_HDFS=1
SET PYARROW_WITH_DATASET=1
SET PYARROW_WITH_FLIGHT=1
SET PYARROW_WITH_GANDIVA=0
SET PYARROW_WITH_ORC=1
SET PYARROW_WITH_PARQUET=1
SET PYARROW_WITH_PARQUET_ENCRYPTION=1
SET PYARROW_CMAKE_GENERATOR=Ninja
@rem CUDA support
set "PYARROW_WITH_CUDA=0"
if defined gpu_variant (
    echo %gpu_variant% | findstr /b "cuda" >nul && set "PYARROW_WITH_CUDA=1"
)
SET PYARROW_WITH_AZURE=0
SET PYARROW_WITH_GCS=0
SET PYARROW_GENERATE_COVERAGE=0
SET PYARROW_BUNDLE_ARROW_CPP=0
SET PYARROW_BUNDLE_CYTHON_CPP=0
"%PYTHON%" -m pip install . -vv --no-deps --no-build-isolation

if errorlevel 1 exit 1
popd
