MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.13"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.13"                # [osx and x86_64]


numpy:
  # python 3.7-3.9
  - 1.16    # [not (osx and arm64)]
  - 1.16    # [not (osx and arm64)]
  - 1.16    # [not (osx and arm64)]
  # python 3.8-3.9
  - 1.19    # [osx and arm64]
  - 1.19    # [osx and arm64]
  # python 3.10
  - 1.21
