{% set version = "0.10.0" %}
{% set commit = "07f142df646c9070fc9c627004dfdc96914fe487" %}
{% set checksum = "ec8494f1906a2919d1eaa9445c97f88eacd38695bfbc5ae5f44315bcbbd6e609" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/arrow/archive/{{ commit }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 2
  skip: true  # [win32 or (win and vc<14)]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake

  host:
    - python
    - setuptools
    - setuptools_scm
    - cython
    - numpy 1.11.*  # [not (win and py>=36)]
    - numpy 1.12.*  # [win and py>=36]
    - six
    - arrow-cpp {{ version }}
    - parquet-cpp

  run:
    - python
    - setuptools
    - {{ pin_compatible("numpy") }}
    - pandas
    - six
    - futures  # [py27]

test:
  imports:
    - pyarrow
    - pyarrow.parquet
    - pyarrow.plasma  # [unix]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - jreback
    - cpcloud
    - pcmoritz
    - robertnishihara
    - siddharthteotia
    - kou
    - msarahan
