{% set version = "10.0.1" %}
{% set filename = "apache-arrow-" + version + ".tar.gz" %}
{% set checksum = "c814e0670112a22c1a6ec03ab420a52ae236a9a42e9e438c3cbd37f37e658fb3" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://dist.apache.org/repos/dist/release/arrow/arrow-{{ version }}/{{ filename }}
  sha256: {{ checksum }}

build:
  number: 0
  # arrow-cpp is not available for s390x, see arrow-cpp-feedstock for details.
  skip: true  # [s390x or py<37]

requirements:
  build:
    - cmake
    - ninja
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # directly pin boost-cpp as we also seem to directly include boost symbols
    # in the Python modules.
    - arrow-cpp {{ version }}
    - boost-cpp
    - cython
    - grpc-cpp
    - numpy
    - pip
    - python
    - setuptools
    - setuptools_scm
    - uriparser
    - wheel
  run:
    # - {{ pin_compatible('arrow-cpp') }}
    - arrow-cpp >=10.0.0,<11.0a0
    - {{ pin_compatible('numpy', lower_bound='1.16.6') }}
    - boost-cpp
    - glog
    - python
    - snappy

test:
  imports:
    - pyarrow
    - pyarrow.dataset
    - pyarrow.flight
    - pyarrow.orc
    - pyarrow.parquet
    - pyarrow.fs
    - pyarrow._s3fs
    - pyarrow._hdfs
  commands:
    - test ! -f ${SP_DIR}/pyarrow/tests/test_array.py       # [unix]
    - if exist %SP_DIR%/pyarrow/tests/test_array.py exit 1  # [win]

about:
  home: https://github.com/apache/arrow
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Python libraries for Apache Arrow'
  description: |
    This library provides a Python API for functionality provided by the Arrow C++ libraries, 
    along with tools for Arrow integration and interoperability with pandas, NumPy, and other 
    software in the Python ecosystem.
  dev_url: https://github.com/apache/arrow/tree/master/python
  doc_url: https://github.com/apache/arrow/blob/master/docs/source/developers/python.rst

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - jreback
    - cpcloud
    - pcmoritz
    - robertnishihara
    - siddharthteotia
    - kou
    - kszucs
    - pitrou 
