{% set version = "6.0.1" %}
{% set filename = "apache-arrow-" + version + ".tar.gz" %}
{% set checksum = "3786b3d2df954d078b3e68f98d2e5aecbaa3fa2accf075d7a3a13c187b9c5294" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://dist.apache.org/repos/dist/release/arrow/arrow-{{ version }}/{{ filename }}
  sha256: {{ checksum }}

build:
  number: 3
  skip: true  # [win32]
  skip: true  # [win and py<35]
  entry_points:
    - plasma_store = pyarrow:_plasma_store_entry_point
  ignore_run_exports:
    - glog
    - snappy
    - grpc-cpp
requirements:
  build:
    - cmake
    - ninja
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # directly pin boost-cpp as we also seem to directly include boost symbols
    # in the Python modules.
    - arrow-cpp {{ version }}
    - boost-cpp
    # - clangdev
    - cython
    - grpc-cpp
    - numpy
    - pip
    - python
    - setuptools
    - setuptools_scm
    - six
    - uriparser
    - wheel
  run:
    - {{ pin_compatible('arrow-cpp') }}
    - {{ pin_compatible('numpy', lower_bound='1.16.6') }}
    - boost-cpp
    - glog
    - pandas
    - python
    - six
    - snappy
    - gflags  # [unix]

test:
  imports:
    - pyarrow
    - pyarrow.dataset
    - pyarrow.flight
    # - pyarrow.gandiva
    - pyarrow.orc      # [unix]
    - pyarrow.parquet
    - pyarrow.plasma   # [unix]
    - pyarrow.fs
    - pyarrow._s3fs
    - pyarrow._hdfs
  commands:
    - test ! -f ${SP_DIR}/pyarrow/tests/test_array.py                         # [unix]
    - if exist %SP_DIR%/pyarrow/tests/test_array.py exit 1                    # [win]

about:
  home: http://github.com/apache/arrow
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Python libraries for Apache Arrow'
  dev_url: https://github.com/apache/arrow/tree/master/python
  doc_url: https://github.com/apache/arrow/blob/master/docs/source/developers/python.rst

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - jreback
    - cpcloud
    - pcmoritz
    - robertnishihara
    - siddharthteotia
    - kou
    - kszucs
    - pitrou
