{% set version = "3.0.0" %}
{% set filename = "apache-arrow-" + version + ".tar.gz" %}
{% set checksum = "73c2cc3be537aa1f3fd9490cfec185714168c9bfd599d23e287ab0cc0558e27a" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://dist.apache.org/repos/dist/release/arrow/arrow-{{ version }}/{{ filename }}
  sha256: {{ checksum }}

build:
  number: 0
  skip: true  # [win32]
  skip: true  # [win and py<35]

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # directly pin boost-cpp as we also seem to directly include boost symbols
    # in the Python modules.
    - arrow-cpp {{ version }}
    - boost-cpp
    # - clangdev
    - cython
    - grpc-cpp
    - numpy
    - python
    - setuptools
    - setuptools_scm
    - six
    - uriparser

  run:
    - {{ pin_compatible('arrow-cpp') }}
    - {{ pin_compatible('numpy', lower_bound='1.11') }}
    - boost-cpp
    - futures  # [py==27]
    - glog
    - pandas
    # empty parquet-cpp metapackage, force old versions to be uninstalled
    # - parquet-cpp 1.5.1.*
    - python
    - six
    - snappy

test:
  imports:
    - pyarrow
    - pyarrow.flight   # [not py==27]
    # - pyarrow.gandiva  # [not py==27]
    - pyarrow.orc      # [unix]
    - pyarrow.parquet
    - pyarrow.plasma   # [unix]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - jreback
    - cpcloud
    - pcmoritz
    - robertnishihara
    - siddharthteotia
    - kou
    - kszucs
    - pitrou
