{% set version = "0.11.0" %}
{% set checksum = "1838faa3775e082062ad832942ebc03aaf95386c0284288346ddae0632be855d" %}


package:
  name: pyarrow
  version: {{ version }}

source:
  url: http://apache.cs.utah.edu/arrow/arrow-{{ version }}/apache-arrow-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  skip: true  # [linux32 or win32 or (win and vc<14)]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake

  host:
    - python
    - setuptools
    - setuptools_scm
    - cython
    - numpy-devel   # [not (win and py>=36)]
    - six
    - arrow-cpp {{ version }}

  run:
    - python
    - setuptools
    - pandas
    - six
    - futures  # [py27]

test:
  imports:
    - pyarrow
    - pyarrow.parquet
    - pyarrow.plasma  # [unix]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - jreback
    - cpcloud
    - pcmoritz
    - robertnishihara
    - siddharthteotia
    - kou
    - msarahan
