# Note that this feedstock must be paired with bumping the version of
# `arrow-cpp-feedstock` and the SHA-256 hashes should match between the packages.
{% set name = "pyarrow" %}
{% set version = "18.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/arrow/arrow-{{ version }}/apache-arrow-{{ version }}.tar.gz
  sha256: 2dc8da5f8796afe213ecc5e5aba85bb82d91520eff3cf315784a52d0fa61d7fc

build:
  number: 0
  skip: true  # [py<39]
  rpaths:
    - lib/
    - {{ SP_DIR }}/pyarrow
  missing_dso_whitelist:
    # These can be found in {{ SP_DIR }}, see the tests below
    - "*/libarrow_python{{ SHLIB_EXT }}"         # [unix]
    - "*/libarrow_python_flight{{ SHLIB_EXT }}"  # [unix]
    - "*/arrow_python.dll"                       # [win]
    - "*/arrow_python_flight.dll"                # [win]
    - "*/arrow_python_parquet_encryption.dll"    # [win]

requirements:
  build:
    - cmake
    - ninja
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - arrow-cpp {{ version }}
    - cython >=0.29.31
    - numpy {{ numpy }}
    - pip
    - python
    - setuptools >=64
    # setuptools_scm[toml]>=8
    - setuptools_scm >=8
    - toml
    - wheel
  run:
    - numpy >=1.25,<3
    - python

test:
  imports:
    - pyarrow
    - pyarrow.compute
    - pyarrow.acero
    - pyarrow.csv
    - pyarrow.dataset
    - pyarrow.flight
    - pyarrow.json
    - pyarrow.orc
    - pyarrow.parquet
    - pyarrow.fs
    - pyarrow._s3fs
    - pyarrow._hdfs
  commands:
    - pip check
    - test ! -f ${SP_DIR}/pyarrow/tests/test_array.py       # [unix]
    - if exist %SP_DIR%/pyarrow/tests/test_array.py exit 1  # [win]
    - test -f ${SP_DIR}/pyarrow/libarrow_python_flight${SHLIB_EXT}  # [unix]
    - test -f ${SP_DIR}/pyarrow/libarrow_python${SHLIB_EXT}  # [unix]
    - if not exist %SP_DIR%\pyarrow\arrow_python.dll exit 1                   # [win]
    - if not exist %SP_DIR%\pyarrow\arrow_python_flight.dll exit 1            # [win]
  requires:
    - pip

about:
  home: https://github.com/apache/arrow
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Python libraries for Apache Arrow
  description: |
    This library provides a Python API for functionality provided by the Arrow C++ libraries, 
    along with tools for Arrow integration and interoperability with pandas, NumPy, and other 
    software in the Python ecosystem.
  dev_url: https://github.com/apache/arrow/tree/main/python
  doc_url: https://github.com/apache/arrow/blob/main/docs/source/developers/python.rst

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - jreback
    - cpcloud
    - pcmoritz
    - robertnishihara
    - siddharthteotia
    - kou
    - kszucs
    - pitrou 
