travis:
  secure:
    BINSTAR_TOKEN: uLBOXlhs4AjZ5nJS+3AuWI26iuu+z6YZ0o91RD0VGWP3yR7mYwOADcvPrFs/4xEQW/GzR77/4PN2cF4aM6TjNTxKcQe4ziKtxeEWXzhHWG40IZTzGXoAoT8cUSeBxCJDL2Ul1f2vHeJpIl/on6qI/HD069z1t8m/R6kOYHWGkXQWOaqYpH569hkjvP/jgFBK1OjY51ELmOS+kqdLXIuGtEOE53jwbeMZsn0Jbf3DjFpKa+R1R/GQfTbdQ+OD0AgxzRYny8HS0jxIN288TEWU/xxqHbJSOHgxaDheTkEMx4CFXC4SxDaFUZYFB5Xl/Wt36wZgW888KyaYdsE7yYyTRHD1s1SU2vLxVnFyZPqY+PtUxTiWNbHnjYE7J3AKVDDrSmtv44AJyAvqTuUbXGmFGhY2ABKjl7KGar8LfLTGLpoXfLn3VCOE61cM0SpfOB0nr+p8IwBDjczXna97cHg6wLLSFaFONcUFhCtzsTsGUcz5QYkUkyJuc7+podSLxQN0jzTayvdBaOGqGV4rKeqRLydGAU+ZBzuyfIBYCJahJOVCJO6ixL9ewRcSafiB2vENBoIKFJ4/4yVDY6o5OYpkCVU4kpFCXzSn1SbwcYaSOnaphO+lDxa2YQrPNz641yYmoxwsyt7Dl0nMEw09c3SVdl3bQgJ7Fs3Cd4ydDiOm9iA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
