travis:
  secure:
    BINSTAR_TOKEN: L3jriu2UK644Orya6yPmgmRmk140X45Z9rsIqaQWgAXdYsTG1sWRgfm8Gwjfv9DanSM3DSUnrZa5IV8x8IkenjUVXzU4SMgFFIUOWPqV3gQZ6Rk7wBWZLFK1md3jZNIgo6klioVBYfABdP4t0e89K3heyBIWJHndPTJdz8zWUs5z54/0/JR0iIRIVi+jhN7PAF2aubOChi/+uZm7LGMlsthkPVMQm6xapsfjU6fZIaDvBI3K5f0h4CdUoIo2a/cVkGCZyZn5AXdVT5oCfVL65W3rifyvpQtj1OrRDfjpKZGnseJPYZ7qvPDxth8FtCN3Zu7tky5sBt8Z2HMCd9ofIj+UpLK5EdEsGM0QsjBJft16BYQkJd/IQ0Ls0x5CH2hQZVE/AcEqXVhVJMaHHk/VJ14ohoHT26UspjGG5n51sxY9C3j1ASTtYuptzUjqMnSeRXVbcV3jqsGPCosGGqT0AKE0huxITiBaWUUcFZMdTztCOd6EGfYcds6FN/nfhqCuAqI8Hgqfwbfc4g5EY1+y8zWG9DgaRmqPiCX6hMAi0SO1dR2pXS+tLSEE98yuqUtU56MwHP1dYS/57sD9BLxw6unbWMAQPXNE93TKvNWJh409TLOnEPCwCAfEZp1JJxIIS7ZeMIouYlOOacQFxApfdLJxUaeAgYNmjBpxTdab6gY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
