travis:
  secure:
    BINSTAR_TOKEN: PbK/wjLq5iC2I8vXlHCRGpDkJ1DJYLuJY9ECcjYcf1zXJbnIwzdgLTa35ykgvv+4n62bKfc3cQZKwMdnN9F2M6jIlwFAavy/K4lI4En/Oub5nwknWm7nd7OEdfu0ivzinLMDOxbbpNr4lXmUXp6CHIICrdK68LMeqOnGO/GhptvWebVRozON+R+abF0QVdJkLgQoq+l+JLnaLIdit5VR/uw4VtAudpgz81H4a6cgExSQktUuF0antkvlRlq5MW4I3nYlCNh9J6ByAtaUp3NHudexFpPzTQCG6ioxWzO2p0NAmBFgwVW/wqiKwwSL9dvgUv6E/Iv/hGOZ/xvOrtpHmk1ci8k5YNLOe5AJufLbPQy/qDWaJ3lS46p9ihyTQu35WtrdHTmmlL5PGrxPVpwj5iM9jy1yWhgdeKghyXeUdUCQ9qZDjYLqS133kqnKu5Yoor+7jBeflaQQGazmXbtr0T/ZklGgVjcDaYSilWPRb1V9KgGEsp7NlkGXHJtn89aGGH6fSRkCR++85do4TGJHyxk6YNXRDqN3suxHXwAvOh0qe4rPPbMIGE8Iyc7iXFzyqataMo/D6Un2QWDIBYFgTNc9PveTc5Rb9Ifd3b5V+b7XcOfIsclDBbIUYDa1Ovp9DGkGL3cLGMFR9nkw6dT1yapyB9IAOHvKaPS40m4B39I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
