travis:
  secure:
    BINSTAR_TOKEN: pQxa61C7sRSaWVJaZyQIuK+/wbyBnXc18abv3Tbz7aTc162TQlHYHqfwoz7dbPeSsCj3oMa5PWQKreNEBTZEZi7R/5nIqeIqaqD720PdqUoIdX9c/FRyOCisLqbvvvTNyPu3WAmk8jEERIUx36WA2aGdi1yac83XZefUP1Dik1pOdmRnUAPyWRBK48w3JYKI1rS4x4XWb2VD7AsyrMBcNu34teDTD5halXZuDI3xoAiqSmEb04+mWvrQ9U5wDjTqBE4qKNURAY8fA92lUSyd9RtlhW/5UPSkVTfvm2o+WEkTtCknk2eDqo4W1V7IiEdlDYiuZeUyQ0K8FT97mIpnIuX6Bpje6+tLtTuY4RiUFj46gD0Im+wHy7Pxd2xeJmXtSdCuBA58zf+g5Q11PR8fUcn+CQgUs7L9yo/Swt0jhO5uCcR9huXdS/8ruQSpy+282aEz8wLZylY9jL94HRpnw1dmvGK1V5hUFDnfpUMnXqvgIhECLRi0QEeJQC0mDGFFsFrRT2WzwRBM8EAcmKDUkuHx5f3LK0a2iLcoZd2Z3BCkvythQxqc2DZpxqwSM8jm/R8qIlVjeXr2gprVrUSKmLTuiwplwB4TUklhHmTb9Mk+Np1jf3I+5h1c9N4YJPNE+71EXzQyXRgJCBgOfD3EkJp/r0oc4k+LOk9nAkdWrgc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
